-- Migrating to platform_* to avoid conflict with existing chat system
CREATE TABLE IF NOT EXISTS platform_chats (
    id TEXT PRIMARY KEY, 
    platform TEXT NOT NULL, 
    external_id TEXT NOT NULL, 
    client_name TEXT,
    last_message TEXT,
    unread_count INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'::jsonb,
    UNIQUE(platform, external_id)
);

CREATE TABLE IF NOT EXISTS platform_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id TEXT REFERENCES platform_chats(id) ON DELETE CASCADE,
    external_message_id TEXT,
    text TEXT,
    sender TEXT, -- 'client', 'shop', 'system'
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    platform_data JSONB DEFAULT '{}'::jsonb,
    UNIQUE(chat_id, external_message_id) 
);

CREATE INDEX IF NOT EXISTS idx_platform_chats_platform_external ON platform_chats(platform, external_id);
CREATE INDEX IF NOT EXISTS idx_platform_messages_chat_id ON platform_messages(chat_id);

-- Enable Realtime for these tables SAFELY
DO $$
BEGIN
  -- Create publication if missing
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;

  -- Add tables one by one only if they are not already in the publication
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'platform_chats'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE platform_chats;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'platform_messages'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE platform_messages;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'orders'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE orders;
  END IF;
END $$;